### ISSUE TITLE
Startup probe is failing due to NetPol blocks nodeport ip

### ISSUE THREAD

**Issue by atilsensalduz** [aws/aws-network-policy-agent#108]
Hello, 

I've encountered an issue with NetPol. It blocks the startup probe even after upgrading the VPC CNI version to 1.15.1, and my agent version is 1.0.4. Unfortunately, my startup probe is still failing, and it appears to be blocked by a network policy. Bcz when I delete netpol, startup probe is passed. Is there something I might be missing or overlooking? 

Thanks in advance

_Startup probe failed: Get "http://10.0.30.183:8080/actuator/health/liveness": dial tcp 10.0.30.183:8080: connect: connection refused_

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: service-network-policy
  name: service
  namespace: dev
spec:
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
    - ports:
        - port: 4317
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: opentelemetry
          podSelector:
            matchLabels:
              app.kubernetes.io/component: opentelemetry-collector
    - ports:
        - port: 443
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: default
          podSelector:
            matchLabels:
              component: apiserver
              provider: kubernetes
    - ports:
        - port: 8080
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: maintenance-service
    - ports:
        - port: 8080
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: metric-service
  podSelector:
    matchLabels:
      app.kubernetes.io/name: service
  policyTypes:
    - Ingress
    - Egress

```
