### ISSUE TITLE
Network Policy agent reconciler crashes with a runtime error when pod name contains dot(.) .

### ISSUE THREAD

**Issue by ibnjunaid** [aws/aws-network-policy-agent#118]
**What happened:**
Network Policy agent crashes when pod name contains . (dot) with the following runtime error.
```
Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference
```

Attached logs:
```log
NAMESPACE     NAME                              READY   STATUS             RESTARTS      AGE
default       sample-app.app-7c547489fb-gmnj9   1/1     Running            0             3m46s
kube-system   aws-node-nmxkh                    1/2     CrashLoopBackOff   5 (54s ago)   4m23s
kube-system   coredns-664b6f5f5c-9kq9w          1/1     Running            0             46h
kube-system   coredns-664b6f5f5c-jhzmm          1/1     Running            0             46h
kube-system   kube-proxy-7g9qg                  1/1     Running            0             5h1m
```

```
 containerStatuses:
  - containerID: containerd://62da97335e19f10f460f78b12dea2a60e0a8e3938a6a7e5f38b7e72e00fff4cf
    image: 602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon/aws-network-policy-agent:v1.0.2-eksbuild.1
    imageID: 602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon/aws-network-policy-agent@sha256:71fbb862ba51217f4c8a22502cba6fa8baa098b80590ea753378694b7c82a4db
    lastState:
      terminated:
        containerID: containerd://62da97335e19f10f460f78b12dea2a60e0a8e3938a6a7e5f38b7e72e00fff4cf
        exitCode: 2
        finishedAt: "2023-10-30T09:55:23Z"
        reason: Error
        startedAt: "2023-10-30T09:55:23Z"
    name: aws-eks-nodeagent
    ready: false
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=aws-eks-nodeagent pod=aws-node-nmxkh_kube-system(ba6898d2-9c89-45e3-8202-2d97012e760f)
        reason: CrashLoopBackOff
```

```json
{"level":"info","timestamp":"2023-10-30T09:46:22.273Z","msg":"Starting EventSource","controller":"policyendpoint","controllerGroup":"networking.k8s.aws","controllerKind":"PolicyEndpoint","source":"kind source: *v1alpha1.PolicyEndpoint"}
{"level":"info","timestamp":"2023-10-30T09:46:22.273Z","msg":"Starting Controller","controller":"policyendpoint","controllerGroup":"networking.k8s.aws","controllerKind":"PolicyEndpoint"}
{"level":"info","timestamp":"2023-10-30T09:46:22.384Z","msg":"Starting workers","controller":"policyendpoint","controllerGroup":"networking.k8s.aws","controllerKind":"PolicyEndpoint","worker count":1}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Received a new reconcile request","req":{"name":"deny-all-ingress-rcsxk","namespace":"default"}}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Processing Policy Endpoint  ","Name: ":"deny-all-ingress-rcsxk","Namespace ":"default"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Found a matching Pod: ","name: ":"sample-app.app-7d6fd579dd-tm7gn","namespace: ":"default"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Derived ","Pod identifier: ":"sample-app.app-7d6fd579dd-default"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Total number of PolicyEndpoint resources for","podIdentifier ":"sample-app.app-7d6fd579dd-default"," are ":1}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Deriving Firewall rules for PolicyEndpoint:","Name: ":"deny-all-ingress-rcsxk"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Total no.of - ","ingressRules":0,"egressRules":0}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Default Deny enabled on Ingress"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"No Egress rules and no egress isolation - Appending catch all entry"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"controllers.policyEndpoints","msg":"Processing Pod: ","name:":"sample-app.app-7d6fd579dd-tm7gn","namespace:":"default","podIdentifier: ":"sample-app.app-7d6fd579dd-default"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"ebpf-client","msg":"AttacheBPFProbes for","pod":"sample-app.app-7d6fd579dd-tm7gn"," in namespace":"default"," with hostVethName":"enifccdc72df53"}
{"level":"info","timestamp":"2023-10-30T09:46:22.385Z","logger":"ebpf-client","msg":"Load the eBPF program"}
{"level":"info","timestamp":"2023-10-30T09:46:22.386Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"policyendpoint","controllerGroup":"networking.k8s.aws","controllerKind":"PolicyEndpoint","PolicyEndpoint":{"name":"deny-all-ingress-rcsxk","namespace":"default"},"namespace":"default","name":"deny-all-ingress-rcsxk","reconcileID":"988d852f-07fb-4ef2-9dfa-b21f263699ab"}
```

Sample Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: sample-app
  name: sample-app.app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sample-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: sample-app
    spec:
      serviceAccountName: default
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          resources: {}
```

Sample Policy:

```yaml

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress
spec:
  podSelector: 
    matchLabels: {}
  policyTypes: ["Ingress"] 
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: run
                values: 
                  - ns1
                  - ns2
                  - ns3
                operator: In
```
