### ISSUE TITLE
Is the network policy for VPC CNI designed to be stateful or stateless?

### ISSUE THREAD

**Issue by khayong** [aws/aws-network-policy-agent#175]
**What happened**:

I have created an egress network policy allowing the web pod to establish connections with the backend server pod at port 4000. 
```
podSelector:
    matchLabels:
      app.kubernetes.io/component: web
egress:
    - ports:
        - protocol: TCP
          port: 4000
      to:
       - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: backend
         podSelector:
            matchLabels:
              app.kubernetes.io/name: backend
```
While initially operating as intended, after some time, the packet log occasionally registers a DENY entry for certain return traffic.
```
Node: ip-10-0-64-172.ap-southeast-1.compute.internal;SIP: 10.0.68.172;SPORT: 4000;DIP: 10.0.74.123;DPORT: 39816;PROTOCOL: TCP;PolicyVerdict: DENY
```
where 10.0.68.172 is the backend server, 10.0.74.123 is the web server.

To mitigate this issue, I have to define an ephemeral port range for the ingress of the returned traffic, similar to the VPC ACL configuration.
```
podSelector:
    matchLabels:
      app.kubernetes.io/component: web
ingress:
    - ports:
        - protocol: TCP
          port: 1024
          endPort: 65535
      from:
       - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: backend
         podSelector:
            matchLabels:
              app.kubernetes.io/name: backend
```

**Attach logs**

**What you expected to happen**:
Kubernetes Network Policies are stateful, which means there's often no need to explicitly define rules for return traffic?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: v1.28.4-eks-8cb36c9`
- CNI Version: `v1.16.0-eksbuild.1`
- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
SUPPORT_END="2025-06-30"
```
- Kernel (e.g. `uname -a`): `Linux ip-10-0-64-172.ap-southeast-1.compute.internal 5.10.199-190.747.amzn2.x86_64 aws/amazon-vpc-cni-k8s#1 SMP Sat Nov 4 16:55:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
