### ISSUE TITLE
Ingress rule with named port not resolving to numerical port on target Pod in PolicyEndpoint

### ISSUE THREAD

**Issue by yndai** [aws/aws-network-policy-agent#193]
**What happened**:

Summary: When creating a `NetworkPolicy` with an ingress rule that allows traffic to a named port on a target pod, the ingress rule is not created in the resulting `PolicyEndpoint` (and traffic is not allowed either).

Additional details:
- Explicitly specifying the numerical target port in the `NetworkPolicy` works fine
- If the source of the ingress is a `Pod` and _that_ source `Pod` has the **same named ports**, the rule also works fine (regardless of the numerical values declared in the source pod) (See the "Anything else we need to know" section)

**What you expected to happen**:

When specifying a named port in a `NetworkPolicy` rule, the port should be mapped to the corresponding numerical port on the target `Pod`, if available.

**How to reproduce it (as minimally and precisely as possible)**:

Example:

`kubctl apply -f` on:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: target
  labels:
    app: target
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
      name: web-service # Named port
    - containerPort: 443
      name: s-web-service # Named port
---
apiVersion: v1
kind: Pod
metadata:
  name: source
  labels:
    app: source
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-traffic
spec:
  podSelector:
    matchLabels:
      app: target
  policyTypes:
  - Ingress
  ingress:
    - from:
      - ipBlock:
          cidr: 172.17.0.0/16
      ports:
      - protocol: TCP
        port: web-service # Named port
    - from:
      - podSelector:
          matchLabels:
            app: source
      ports:
      - protocol: TCP
        port: s-web-service # Named port
```

We expect this in the resulting`PolicyEndpoint`: 

```yaml
apiVersion: networking.k8s.aws/v1alpha1
kind: PolicyEndpoint
metadata:
  name: allow-web-traffic-fjz4q
 [...]
spec:
  ingress:
  - cidr: 172.17.0.0/16
    ports:
    - port: 80
      protocol: TCP
  - cidr: <source Pod IP>
    ports:
    - port: 443
      protocol: TCP
[...]
```

**But instead got this:**

```yaml
apiVersion: networking.k8s.aws/v1alpha1
kind: PolicyEndpoint
metadata:
  name: allow-web-traffic-fjz4q
 [...]
spec:
  ingress: []
[...]
```

**Anything else we need to know?**:

Another weirdness: if the source `Pod` has the named ports in the ingress rule on the target `Pod`, the named port rule that specifies the source `Pod` actually works as expected!

e.g. if you delete the source pod in the above example and apply this instead:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: source
  labels:
    app: source
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 8000 # Irrelevant
      name: web-service   # Named port
    - containerPort: 8443 # Irrelevant
      name: s-web-service # Named port
```

We now get:
```yaml
apiVersion: networking.k8s.aws/v1alpha1
kind: PolicyEndpoint
metadata:
  name: allow-web-traffic-fjz4q
 [...]
spec:
  ingress:
  - cidr: <source Pod IP>
      ports:
      - port: 443
        protocol: TCP
[...]
```

The CIDR source rule is still missing, however. This makes me think that there is an incorrect check against the source `Pod` when mapping named ports to their numerical values instead of the target `Pod`.

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.8-eks-8cb36c9", GitCommit:"fca3a8722c88c4dba573a903712a6feaf3c40a51", GitTreeState:"clean", BuildDate:"2023-11-22T21:52:13Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}`
- CNI Version: `amazon-k8s-cni:v1.16.0-eksbuild.1`
- Network Policy Agent Version: `aws-network-policy-agent:v1.0.7-eksbuild.1`
- OS (e.g: `cat /etc/os-release`): `Amazon Linux 2`
- Kernel (e.g. `uname -a`): `Linux ip-10-1-61-179.ec2.internal 5.10.192-183.736.amzn2.x86_64 #1 SMP Wed Sep 6 21:15:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
