### ISSUE TITLE
High network usage to Kubernetes API

### ISSUE THREAD

**Issue by gnuletik** [aws/aws-network-policy-agent#211]
**What happened**:

We have the following kind of NetworkPolicy in our cluster:

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: some-name
  namespace: app-namespace
spec:
  podSelector: {}
  ingress:
    - {}
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16

    - to:
        - ipBlock:
            cidr: some-cidr

    # allow kube-dns
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP

    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: other-namespace
          podSelector:
            matchLabels:
              app: some-app
      ports:
        - protocol: TCP
          port: 8000
```

When there's ~500 nodes in the cluster, the `aws-eks-nodeagent` containers receives a lot of traffic from the Kubernetes API, around 300MB/s across all nodes.

This lead to a lot of packet drops by EC2, triggered by `pps_allowance_exceeded` errors.

<img width="1055" alt="Screenshot 2024-02-14 at 16 29 47" src="https://github.com/aws/aws-network-policy-agent/assets/9059840/a693283c-640c-43d5-80a4-016cf59e752f">

**Attach logs**

**What you expected to happen**:

Reduced network usage to avoid `pps_allowance_exceeded` errors. 

**How to reproduce it (as minimally and precisely as possible)**:

Setup a similar NetworkPolicy and add nodes to the cluster.

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.28.5-eks-5e0fdde`
- CNI Version: [`v1.16.2`](https://github.com/aws/amazon-vpc-cni-k8s/releases/tag/v1.16.2)
- Network Policy Agent Version: `v1.0.7`
- OS (e.g: `cat /etc/os-release`): [EKS AMI v20240202](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240202)
- Kernel (e.g. `uname -a`): `5.10.205-195.807.amzn2`
