### ISSUE TITLE
Network denies despite allow-all policy (strict mode)

### ISSUE THREAD

**Issue by creinheimer** [aws/aws-network-policy-agent#288]
Hello,

For several weeks we've been working on implementing network policies using the AWS solution. However, we've encountered various challenges along the way. Initially, we discovered that using the `standard` enforcement mode could lead to network instability. As a result, we decided to use the so called `strict` mode.

In this thread https://github.com/aws/aws-network-policy-agent/issues/271#issuecomment-2183294414, @achevuru suggested that we could create an `allow all` policy for each namespace and that the only side effect would be the deny mode during the first seconds of a newly launched pod. We then created an allow all policy on all namespaces and enabled the annotate Pod IP flag to allow faster network policy evaluations. 

Now we have a new issue: pods in namespaces with an allow-all network policy are still experiencing network denies. This isn't limited to the initial startup period. It's happening long after pods have been running, sometimes hours later.

This behaviour is causing different problems, including pod crashes. In some cases, even the pod's internal health checks are being denied, triggering unnecessary restarts.

Can you provide any insight into why this might be happening? Am I missing something?

**More info:**

<details>
  <summary>Deny logs from pods to control-plane</summary>

![image](https://github.com/user-attachments/assets/037ac8ec-5256-4d26-8e24-809b4f88d7da)

</details>

<details>
  <summary>Deny logs from pods to pods on same namespace</summary>

![image](https://github.com/user-attachments/assets/f950adbe-11b4-46a2-9127-daccafddcc93)

</details>

These are just a few of them. We had approx. 200 denies over last 15 minutes.

<details>
  <summary>NetworkPolicy allow-all </summary>
  
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  finalizers:
  - networking.k8s.aws/resources
  name: allow-all
  namespace: kube-prometheus-stack
spec:
  egress:
  - {}
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress

```
</details>

**Environment**:
- Kubernetes: `v1.29.4-eks-036c24b`
- CNI Version: `v1.18.1`
- Network Policy Agent Version: `v1.1.2`
- OS: `Amazon Linux 2`
- Kernel: `5.10.215-203.850.amzn2.aarch64`

Our AWS-CNI uses the [default helm-chart](https://github.com/aws/amazon-vpc-cni-k8s/blob/v1.18.1/charts/aws-vpc-cni/values.yaml) with the following variables:

<details>
  <summary>AWS-CNI configuration</summary>

```yaml
env:
  ENABLE_PREFIX_DELEGATION: "true"
  AWS_VPC_K8S_PLUGIN_LOG_FILE: stderr
  AWS_VPC_K8S_PLUGIN_LOG_LEVEL: DEBUG
  AWS_VPC_K8S_CNI_LOG_FILE: stdout
  AWS_VPC_K8S_CNI_LOGLEVEL: DEBUG
  NETWORK_POLICY_ENFORCING_MODE: strict
  ANNOTATE_POD_IP: "true"
```
</details>

**Note:**

@jayanthvn that's follow-up of https://github.com/aws/aws-network-policy-agent/issues/73#issuecomment-2214634920.
