### ISSUE TITLE
High CPU usage during pod churns when NP targets large rules

### ISSUE THREAD

**Issue by viveksb007** [aws/aws-network-policy-agent#417]
**What happened**:
NPA CPU utilization is high during high pod churning load in system.

**What you expected to happen**:
NPA should handle the incremental updates in NP efficiently.

**How to reproduce it (as minimally and precisely as possible)**:

> Test scale:
Tested with commit https://github.com/aws/aws-network-policy-agent/commit/92a9c0f9048b30a4f118df677ba99e0f15e71dc2 and following flags to prevent CPU spikes due to excessive logging
```
- args:
        - --enable-ipv6=false
        - --enable-network-policy=true
        - --enable-cloudwatch-logs=false
        - --enable-policy-event-logs=false
        - --log-level=error
        - --log-file=/var/log/aws-routed-eni/network-policy-agent.log
        - --metrics-bind-addr=:8162
        - --health-probe-bind-addr=:8163
        - --conntrack-cache-cleanup-period=300
        env:
        - name: AWS_EBPF_SDK_LOGLEVEL
          value: error
```

- Cluster with 100 nodes (`m5.large` instance type).
- Created 2 deployments in separate ns (`ns1` and `ns2`) which will each deploy 1000 pods.
- Created 4 similar NP per ns where each NP creates ingress/egress rules targeting other ns
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-np
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: ns1
  - to:
    - namespaceSelector:
        matchLabels:
          name: ns2
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ns1
  - from:
    - namespaceSelector:
        matchLabels:
          name: ns2
  policyTypes:
  - Egress
  - Ingress
```
Created a pod churn of 300 pods every 30sec. 

Created 4 more similar NP per ns, so total of 8 NP per ns. Can see the CPU spiked from before.

### CPU Utilization:

<img width="1084" alt="Image" src="https://github.com/user-attachments/assets/621bf601-2b1a-4ceb-a1be-af79d7247ae6" />

We have profiled and identified some optimization areas in the reconciliation logic. We are working to add those optimizations and bring the CPU usage down during Pod churn load.
