### ISSUE TITLE
Egress policies don't work for egress traffic outside of the cluster

### ISSUE THREAD

**Issue by ConorPKeegan** [aws/aws-network-policy-agent#55]
For IPv6 clusters, all IPv4 egress traffic cannot filtered with policies (and likely vice versa for IPv4 clusters with IPv6 link-local addresses).

## Example (on a clean IPv6 EKS cluster):

Using this policy to deny all egress traffic (except DNS):
```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - port: 53
      protocol: UDP
```

Using this pod to test with:
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: netshoot
  name: netshoot
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot
    command: ["/bin/bash"]
    args: ["-c", "sleep inf"]
```

All IPv6 traffic is blocked from accessing external resources, but IPv4 is not:
```bash
$ kubectl exec -it netshoot -- curl --max-time 3 -I -v example.com
*   Trying [2606:2800:220:1:248:1893:25c8:1946]:80...
*   Trying 93.184.216.34:80...
* Connected to example.com (93.184.216.34) port 80 (#0)
> HEAD / HTTP/1.1
> Host: example.com
> User-Agent: curl/8.0.1
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Accept-Ranges: bytes
Accept-Ranges: bytes
< Age: 192079
Age: 192079
< Cache-Control: max-age=604800
Cache-Control: max-age=604800
< Content-Type: text/html; charset=UTF-8
Content-Type: text/html; charset=UTF-8
< Date: Fri, 08 Sep 2023 15:18:21 GMT
Date: Fri, 08 Sep 2023 15:18:21 GMT
< Etag: "3147526947"
Etag: "3147526947"
< Expires: Fri, 15 Sep 2023 15:18:21 GMT
Expires: Fri, 15 Sep 2023 15:18:21 GMT
< Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
< Server: ECS (nyb/1D06)
Server: ECS (nyb/1D06)
< X-Cache: HIT
X-Cache: HIT
< Content-Length: 1256
Content-Length: 1256

< 
* Connection #0 to host example.com left intact
```

**Comment by vaskozl** [comment]
This is especially prudent given that you can't disable the virtual v4 interfaces creation by the CNI on v6 clusters. 

On v4 clusters you have the option of not enable the veths via [ENABLE_V6_EGRESS](https://github.com/aws/amazon-vpc-cni-k8s/blob/f7672495a1d38807d7ce4def052be577ea171d86/README.md?plain=1#L661), but there is no such alternative on v6 clusters meaning there is no reliable way to selectively block public egress.

If that were possible this issue would be somewhat mitigated.

**Comment by ConorPKeegan** [comment]
>Policy enforcement will not extend to any secondary interfaces pod might have (via chained plugins or Multus) and/or IPs that belong to different IP family than the cluster.

The issue here is that in this case we're not talking about a cluster that has intentionally added an additional interface with chained plugins or Multus, this is just using the base VPC CNI with only the network policies enabled. This surely means that anybody using this on a cluster will run into exactly the same issue, without being able to find any documentation to explain this absolutely huge caveat to the network policies. 

Are there any recommended workarounds for this currently, as it cannot be used in it's current form?

**Comment by achevuru** [comment]
@ConorPKeegan EKS doesn't support dual stack clusters, and `egress-v4` support that EKS currently provides (by default) is via a chained plugin and so the same caveat called out in the above FAQ extends to egress v4 plugin as well. As you might already know, this interface is an egress only interface and the IPv4 IP attached to this interface is not routable beyond the node and is exclusively for egress only support. So, this caveat applies to pods on an IPv6 only cluster trying to reach an IPv4 endpoint via the secondary interface created by the chained plugin. From VPC CNI point of view, we are considering providing an option to disable the chained plugin if there is no need for such an use case in a particular cluster.

Pods on IPv4 clusters will not have any secondary interfaces created by VPC CNI by default and IPv6 Link local addresses are not routable.

**Comment by htyagi-aws** [comment]
I can confirm the behavior reported on this thread -

The behavior on ipv6 cluster is a bit different than ipv4 cluster

**Network Policy that blocks all outgoing traffic**

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: client-one-deny-egress
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: nginx
  egress: []
  policyTypes:
  - Egress

```
**Its behavior On Ipv6 cluster :**

```
root@nginx:/# curl --max-time 3 -I -v example.com
* Resolving timed out after 3000 milliseconds
* Closing connection 0
curl: (28) Resolving timed out after 3000 milliseconds
```

As can be seen above in the first attempt we try to curl using 'name' and since connectivity with kube-dns is blocked via policy the name resolution does not happen and connection fails there. We might think here our use-case is achieved but under the hood ipv4 is still allowed.

To prove this theory we by-pass the DNS name resolution process and hit the ipv4 address directly while policy is still applied as shown in second attempt show below, it is able to establish connection with destination.

```
root@nginx:/# curl --max-time 3 -I -v 93.184.216.34:80
*   Trying 93.184.216.34:80...
* Connected to 93.184.216.34 (93.184.216.34) port 80 (#0)
> HEAD / HTTP/1.1
> Host: 93.184.216.34
> User-Agent: curl/7.88.1
> Accept: */*
> 
* Connection #0 to host 93.184.216.34 left intact
```

Note : 93.184.216.34 is the ipv4 address for example.com.

If we put ipv6 address in the curl request it is still blocked as show below -

```
root@nginx:/# curl --max-time 3 -I -v [2606:2800:220:1:248:1893:25c8:1946]:80
*   Trying [2606:2800:220:1:248:1893:25c8:1946]:80...
* Connection timed out after 3001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 3001 milliseconds
```

This proves that ipv4 traffic isn't blocked on ipv6 cluster even with the simplest of network policies that is supposed to block everything.

**Its behavior on ipv4 cluster :**

```
htxxx@c8xxxxxxxxx-policies % kubectl exec -it nginx-77b4fdf86c-nm8vz  -- curl --max-time 3 -I -v 93.184.216.34:80
*   Trying 93.184.216.34:80...
* Connection timed out after 3001 milliseconds
* Closing connection 0
curl: (28) Connection timed out after 3001 milliseconds
```

As can be seen the ipv4 traffic is blocked on ipv4 cluster with the same network policy even if you directly hit the IP address.
