### ISSUE TITLE
Crashloop backoff on GPU instances (g4dn.xlarge)

### ISSUE THREAD

**Issue by XciD** [aws/aws-network-policy-agent#74]
We are trying this new feature on our dev cluster.

We saw that CPU nodes are working, but the `aws-node` Pod is on `CrashLoopBackOff` only on our gpus nodes.

Logs don't show anything relevant:
```
{"level":"info","ts":"2023-09-25T08:23:41Z","msg":"version","GitVersion":"","GitCommit":"","BuildDate":""}
```

Pod info:
```
  containerStatuses:
  - containerID: containerd://c926cd629dd1330204bbc91c0e5b2742cfbc4c6f744664bd6dc26a9c4742e142
    image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-network-policy-agent:v1.0.2-eksbuild.1
    imageID: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon/aws-network-policy-agent@sha256:71fbb862ba51217f4c8a22502cba6fa8baa098b80590ea753378694b7c82a4db
    lastState:
      terminated:
        containerID: containerd://c926cd629dd1330204bbc91c0e5b2742cfbc4c6f744664bd6dc26a9c4742e142
        exitCode: 1
        finishedAt: "2023-09-25T08:23:41Z"
        reason: Error
        startedAt: "2023-09-25T08:23:41Z"
    name: aws-eks-nodeagent
    ready: false
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=aws-eks-nodeagent pod=aws-node-29l5n_kube-system(15ae1d23-9545-47b3-983d-5ba8784a6ae8)
        reason: CrashLoopBackOff

```

I've tried with `v1.14.0-eksbuild.3` and now with `v1.15.0-eksbuild.2`.

EDIT:

`bpf` folder is mounted

```
[root@ip-10-4-67-63 /]# ls /sys/fs/bpf/
globals
```
