### ISSUE TITLE
Allowing ICMP in network policy

### ISSUE THREAD

**Issue by ankenyr** [aws/aws-network-policy-agent#90]
Currently it seems that ICMP is not allowed as a protocol in a network policy but it seems to be at least partially implemented and planned for.

https://github.com/aws/aws-network-policy-agent/blob/d764cafebca031cadd28eaa962e9af524edb2298/pkg/utils/utils.go#L21
https://github.com/aws/aws-network-policy-agent/blob/d764cafebca031cadd28eaa962e9af524edb2298/pkg/ebpf/events/events.go#L118

However when attempting to use protocol ICMP in the following way

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: cnitest
  name: demo
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 8.8.8.8/32
      ports:
        - protocol: ICMP
```

It results in an error message
`The NetworkPolicy "demo-app-deny-all" is invalid: spec.egress[0].ports[0].protocol: Unsupported value: "ICMP": supported values: "TCP", "UDP", "SCTP"`

This is an issue for any network using IPv6. [RFC4890](https://datatracker.ietf.org/doc/html/rfc4890#section-4.3.1) states that certain ICMP messages should always be allowed while others may be filtered. 

As soon as a filter is applied it negates all ICMP traffic unless the protocol is not specified and even then, only to the network or pods that are targeted. This makes it impossible to allow ICMP within the cluster while only allowing specific ports and protocols for direct communication.
